name: Deploy to Firebase Hosting manually on /deploy
on:
  issue_comment:
    types: [created]
jobs:
  build_and_preview:
    if: github.event.issue.pull_request && github.event.issue_comment.repository == github.repository && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAGELLAN2022_613C2 }}'
          projectId: magellan2022-613c2
